### ISSUE TITLE
Not all the titles are getting imported

### ISSUE THREAD

**Issue by pimbolilu** [crohrer/spotifyRadioPlaylist#5]
If I try to import the titles from a radio station, not all the titles will get added.

"radioTrackserviceUrl": "http://www.eldo.lu/music/charts/chartbreaker/",
"radioEntrySelector": "div.unit",
"radioTitleSelector": "div.u2>h2",
"radioArtistSelector": "div.u2>h3",  
"searchLinear": false,

Debug: the track array from radiocrawler.js is filled up with all the titles, seems that there is a problem in spotifySearch.searchTracks(tracks) but I did not find out why some results are missing. all the titles are available if I search for them manualy on spotify

**Comment by chrisheinzelmann** [comment]
When searching for songs on Spotify you need to make a trade off: more false positives or more false negatives. At first I simply took the first item from the result list. Then I noticed for a lot of songs an unpleasant effect:
Some originals of songs simply don't exist on Spotify. So when you search for one of those non existent songs you often get some weird cover version of that song or even worse: some totally unrelated result that just happens to have the exact same title.
For me it was far more annoying to have those wrong results in my playlist than to get every possible song. So I decided in favor of more false negatives.
I implemented it in the following way:
I decided to use a bit of information that comes with the results: each song has a field with the artist name. This artist name is the best way to identify the correct song. So I do an exact match with the artist name I got from the radio website. Sadly some radio websites use a slightly different name for some artists (like "Beatles" vs. "the Beatles"). 
You could of cause do some optimization here - like removing words like "the" from the results artist field. I didn't do this because it would require a lot of testing (think of cases where the artists name consists of words like "thermals") 
As there are a lot of things that can go wrong with optimizing this I decided to live with the list being not complete but correct.
