### ISSUE TITLE
Feature request: Multiplaylist

### ISSUE THREAD

**Issue by pimbolilu** [crohrer/spotifyRadioPlaylist#6]
Add the possibility to add multiple sources and multiple playlist to congig.json

**Comment by chrisheinzelmann** [comment]
@pimbolilu can you clarify this a bit? Maybe with an example what you want to do exactly

**Comment by pimbolilu** [comment]
Hello,

It would be nice to have the possibility, to configure the script that it can handle multiple soures/playlists.

EX: 
Source :Radio Bremen  -> RadioBremen Playlist
Source: RPR1 -> RPR1 Playlist.

So that in one run all the playlists configured will get updated.

**Comment by chrisheinzelmann** [comment]
This is implemented in the newest Version 2.4.0

Multiple Playlists can now be added to one config file. 
But you can only run one playlist at a time. 
This has technical reasons (currently the script just ends when any serious error happens. This would mean that all subsequent playlists will not get crawled.) and also practical reasons: Different radio stations require different time intervals for crawling. Some Stations must be crawled hourly because they only show the last 20 songs. Others can be crawled once a week.
You can find more details in readme
